export default {
  user: {
    metaData: {
      primaryKeys: ['userId'],
      keys: [['userId']]
    },
    fields: {
      insertedId: {
        key: false,
        path: 'insertedId',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: '_id',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      userId: {
        key: true,
        path: 'userId',
        dataType: 'number',
        autoGenerated: {
          tableId: 'sequence',
          columnName: 'userId'
        },
        tables: [
          {
            tableId: 'user',
            columnName: 'userId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      firstName: {
        key: false,
        path: 'firstName',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: 'fname',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      lastName: {
        key: false,
        path: 'lastName',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: 'lname',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      created: {
        key: false,
        path: 'created',
        dataType: 'date',
        tables: [
          {
            tableId: 'user',
            columnName: 'created',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      orders: {
        key: false,
        path: 'orders',
        domain: 'order',
        isOneToMany: true,
        keys: [['userId']]
      }
    }
  },
  order: {
    metaData: {
      primaryKeys: ['userId'],
      keys: [['userId'], ['orderId']]
    },
    fields: {
      userId: {
        key: true,
        dataType: 'number',
        path: 'userId',
        tables: [
          {
            tableId: 'user',
            columnName: 'userId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      orderId: {
        key: true,
        dataType: 'string',
        path: 'orderId',
        tables: [
          {
            tableId: 'user',
            columnName: 'orderId',
            connectionName: 'modelData' // db connection instance name
          },
          {
            tableId: 'user',
            columnName: 'orderId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      label: {
        key: false,
        path: 'label',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: 'label',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      quantity: {
        key: false,
        dataType: 'number',
        path: 'orderdetails.quantity',
        tables: [
          {
            tableId: 'user',
            columnName: 'quantity',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      price: {
        key: false,
        path: 'orderdetails.price',
        dataType: 'number',
        tables: [
          {
            tableId: 'user',
            columnName: 'price',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      user: {
        key: false,
        path: 'user',
        domain: 'user',
        isOneToMany: false,
        keys: [['userId']]
      }
    }
  }
}