export default {
  // User Entity Definition
  user: {
    // Metadata for User Entity
    metaData: {
      primaryKeys: ['userId'], // Primary key for user entity
      keys: [['userId']] // Index definition for user entity
    },
    // Fields for User Entity
    fields: {
      insertedId: {
        key: false,
        path: 'insertedId',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: '_id',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      userId: {
        key: true, // Primary key
        path: 'userId',
        dataType: 'number',
        // autoGenerated: {
        //   tableId: 'sequence',
        //   columnName: 'userId'
        // },
        tables: [
          {
            tableId: 'user',
            columnName: 'userId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      firstName: {
        key: false,
        path: 'firstName',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: 'fname',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      lastName: {
        key: false,
        path: 'lastName',
        dataType: 'string',
        tables: [
          {
            tableId: 'user',
            columnName: 'lname',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      created: {
        key: false,
        path: 'created',
        dataType: 'date',
        tables: [
          {
            tableId: 'user',
            columnName: 'created',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      orders: {
        key: false,
        path: 'orders',
        domain: 'order',
        isOneToMany: true,
        keys: [['userId']] // Foreign key relationship with user entity
      }
    }
  },
  // Order Entity Definition
  order: {
    // Metadata for Order Entity
    metaData: {
      primaryKeys: ['orderId'], // Primary key for order entity
      keys: [['userId'], ['orderId']] // Index definition for order entity
    },
    // Fields for Order Entity
    fields: {
      userId: {
        key: true, // Primary key
        dataType: 'number',
        path: 'userId',
        tables: [
          {
            tableId: 'user',
            columnName: 'userId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      orderId: {
        key: true, // Primary key
        dataType: 'string',
        path: 'orderId',
        tables: [
          {
            tableId: 'order',
            columnName: 'orderId',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      label: {
        key: false,
        path: 'label',
        dataType: 'string',
        tables: [
          {
            tableId: 'order',
            columnName: 'label',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      quantity: {
        key: false,
        dataType: 'number',
        path: 'quantity',
        tables: [
          {
            tableId: 'order',
            columnName: 'quantity',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      price: {
        key: false,
        path: 'price',
        dataType: 'number',
        tables: [
          {
            tableId: 'order',
            columnName: 'price',
            connectionName: 'modelData' // db connection instance name
          }
        ]
      },
      user: {
        key: false,
        path: 'user',
        domain: 'user',
        isOneToMany: false,
        keys: [['userId']] // Foreign key relationship with user entity
      }
    }
  }
}
